<a href="https://colab.research.google.com/github/rajpatel2619/PyTorch_tutes/blob/develop-REG/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lst = [[1,2,3],[3,4,5]]

In [ ]:
lst

[[1, 2], [3, 4, 5]]

In [ ]:
np.array(lst)

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,4,19)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ,
       2.22222222, 2.44444444, 2.66666667, 2.88888889, 3.11111111,
       3.33333333, 3.55555556, 3.77777778, 4.        ])

In [2]:
import torch
